---
# https://github.com/hyperledger/fabric-sdk-go/blob/master/test/fixtures/config/config_e2e.yaml
name: org1
version: 1.0.0
client:
  organization: Org1
  logging:
    level: error
  connection:
    timeout:
      peer:
        endorser: '300'

organizations:
  OrdererOrg:
    mspid: OrdererMSP
  Org1:
    mspid: Org1MSP
    peers:
      - fabric-peer0.org1.fabric-tendermint-cross-demo.com

channels:
  channel1:
    orderers:
      - fabric-orderer.fabric-tendermint-cross-demo.com
    peers:
      fabric-peer0.org1.fabric-tendermint-cross-demo.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

orderers:
  fabric-orderer.fabric-tendermint-cross-demo.com:
    url: grpc://fabric-orderer.fabric-tendermint-cross-demo.com:7050
    grpcOptions:
      ssl-target-name-override: fabric-orderer.fabric-tendermint-cross-demo.com
      hostnameOverride: fabric-orderer.fabric-tendermint-cross-demo.com
      allow-insecure: true

peers:
  fabric-peer0.org1.fabric-tendermint-cross-demo.com:
    url: grpc://fabric-peer0.org1.fabric-tendermint-cross-demo.com:7051
    grpcOptions:
      ssl-target-name-override: fabric-peer0.org1.fabric-tendermint-cross-demo.com
      hostnameOverride: fabric-peer0.org1.fabric-tendermint-cross-demo.com
      allow-insecure: true

### https://github.com/hyperledger/fabric-sdk-go/blob/master/test/fixtures/config/overrides/local_entity_matchers.yaml
entityMatchers:
  peer:
    - pattern: fabric-peer0.org1.fabric-tendermint-cross-demo.com
      urlSubstitutionExp: localhost:7051
      sslTargetOverrideUrlSubstitutionExp: fabric-peer0.org1.fabric-tendermint-cross-demo.com
      mappedHost: fabric-peer0.org1.fabric-tendermint-cross-demo.com
  orderer:
    - pattern: fabric-orderer.fabric-tendermint-cross-demo.com
      urlSubstitutionExp: localhost:7050
      sslTargetOverrideUrlSubstitutionExp: fabric-orderer.fabric-tendermint-cross-demo.com
      mappedHost: fabric-orderer.fabric-tendermint-cross-demo.com
