#!/usr/bin/env bash
set -eu

source $(cd $(dirname ${BASH_SOURCE:-$0}); pwd)/util/env

## Setup test fixtures

set +x
rm -rf ${FIXTURES_DIR}
mkdir -p ${FIXTURES_DIR}/tendermint/ibc0/config
set -x

## copy tendermint's node mnemonic from node container
${DOCKER} cp tendermint-chain0:/root/data/ibc0/key_seed.json  ${FIXTURES_DIR}/tendermint/ibc0/key_seed.json

# for alphacli
${DOCKER} cp tendermint-chain0:/root/data/ibc0/tokenowner_seed.json ${FIXTURES_DIR}/tendermint/ibc0/
${DOCKER} cp tendermint-chain0:/root/data/ibc0/config/app.toml ${FIXTURES_DIR}/tendermint/ibc0/config/
${DOCKER} cp tendermint-chain0:/root/data/ibc0/config/client.toml ${FIXTURES_DIR}/tendermint/ibc0/config/
${DOCKER} cp tendermint-chain0:/root/data/ibc0/config/config.toml ${FIXTURES_DIR}/tendermint/ibc0/config/
${DOCKER} cp tendermint-chain0:/root/data/ibc0/keyring-test ${FIXTURES_DIR}/tendermint/ibc0/

platform='unknown'
unamestr=`uname`
if [ "$unamestr" = 'Linux' ]; then
	sed -i 's/chain-id = ""/chain-id = "'"ibc0"'"/g' ${FIXTURES_DIR}/tendermint/ibc0/config/client.toml
	sed -i 's/broadcast-mode = "sync"/broadcast-mode = "'"block"'"/g' ${FIXTURES_DIR}/tendermint/ibc0/config/client.toml
else
	sed -i '' 's/chain-id = ""/chain-id = "'"ibc0"'"/g' ${FIXTURES_DIR}/tendermint/ibc0/config/client.toml
	sed -i '' 's/broadcast-mode = "sync"/broadcast-mode = "'"block"'"/g' ${FIXTURES_DIR}/tendermint/ibc0/config/client.toml
fi
