#!/bin/bash

set -eu

source $(cd $(dirname ${BASH_SOURCE:-$0}); pwd)/util/env
source ${SCRIPT_DIR}/util/relayer-util

$RLY tendermint keys show $CHAINID_ONE $RLYKEY

# initialize the light client for {{chain_id}}
$RLY tendermint light init $CHAINID_ONE -f
sleep 5

# add a path between chain0 and chain1
$RLY paths add $CHAINID_ONE $CHAINID_TWO $PATH_NAME --file=./configs/relayer/path.json

$RLY tx clients $PATH_NAME
sleep 5
$RLY tx update-clients $PATH_NAME
sleep 5
# NOTE: wait for state changes by timeout, otherwise cause error
$RLY tx connection $PATH_NAME --timeout "5s"
sleep 5
$RLY tx channel $PATH_NAME --timeout "5s"
sleep 5
